name: isolate_contactor
description: An easy way to create a new isolate, keep it running and comunicate with it. It supports sending values between main and child isolate multiple times via stream.
version: 1.3.0
homepage: https://github.com/vursin/isolate_contactor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stream_channel: ^2.1.0

dev_dependencies:
  test: ^1.17.12
  lints: ^2.0.0
