name: isolate_contactor
description: An easy way to create a new isolate and comunicate with it and support sending values between main and child isolate multiple times via `stream`.
version: 1.1.0+1
homepage: https://github.com/fatasin/isolate_contactor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stream_channel: ^2.1.0

dev_dependencies:
  test: ^1.17.12
  lints: ^1.0.1
