name: isolate_contactor
description: An easy way to create a new Isolate, keep it active and communicate with it (supports `Worker` and `WASM` on the Web platform).
version: 4.2.0
homepage: https://github.com/lamnhan066/isolate_contactor

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  stream_channel: ^2.1.1
  web: ^0.5.1

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
