name: isolate_contactor
description: An easy way to create a new isolate and comunicate with it and support sending values between main and child isolate multiple times via `stream`. So you can build your `widget` with `StreamBuilder` and always listen to the value from your `isolate`.
version: 1.1.0
homepage: https://github.com/fatasin/isolate_contactor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stream_channel: ^2.1.0

dev_dependencies:
  test: ^1.17.12
  lints: ^1.0.1
