name: isolate_contactor
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/fatasin/isolate_contactor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  stream_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dart:

# The following section is specific to Flutter.
flutter: